### ISSUE TITLE
link to us_web_design_standards gem

### ISSUE THREAD

**Issue by afeld** [18F/uswds-rails-gem#1]
https://github.com/18F/us_web_design_standards_gem

...which begs the question: Does it make sense to have them separate?

**Comment by pkarman** [comment]
I think the plan is to completely deprecate https://github.com/18F/us_web_design_standards_gem since it is no longer maintained. @jessieay and I decided to fork a Rails-specific gem rather than try and keep Jekyll support, since we had a hard time finding Jekyll devs to test.

**Comment by pkarman** [comment]
See https://github.com/18F/us_web_design_standards_gem/issues/15 and https://18f.slack.com/archives/ruby/p1470340715000443

**Comment by pkarman** [comment]
https://github.com/18F/us_web_design_standards_gem/issues/15#issuecomment-237958605

**Comment by afeld** [comment]
Fair enough, though I think a note in this README of "are you trying to use the Web Design Standards with Jekyll? Check out ..." and vice versa would be a good thing. Especially since the name of the other one doesn't make it obvious it's Jekyll-specific.

**Comment by pkarman** [comment]
yup see https://github.com/18F/us_web_design_standards_gem/pull/20

**Comment by pkarman** [comment]
fwiw, I don't feel like we can recommend 18F/us_web_design_standards_gem until it is maintained by someone. It is a few revisions of the USWDS assets behind, and we don't seem to have any Jekyll apps actively using it that I am aware of. The comments here suggest the same: https://github.com/18F/us_web_design_standards_gem/pull/19
